version: '3.8'

services:
  web:
    build:
      context: ../
      dockerfile: Dockerfile
    image: raushan0291/cpp-detector-flask
    container_name: flask_app_det
    ports:
      - "5000:5000"
      - "12345:12345"
    devices:
      - "/dev/video0:/dev/video0"
    privileged: true
    volumes:
      - /home/raushan/Documents/Projects/cpp/classifier-cpp/classifier-cpp/11-00-12.ts:/app/11-00-12.ts
    environment:
      - PYTHONUNBUFFERED=1
